name: PR Validation

on:
  pull_request:
    branches: [dev, main]
    types: [opened, synchronize, reopened]

jobs:
  validate-file-extensions:
    name: Validate File Extensions
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check file extensions
      run: |
        echo "Validating file extensions..."
        
        # Check core folder for .py files only
        core_files=$(find core -type f)
        for file in $core_files; do
          if [[ ! $file == *.py ]]; then
            echo "Error: $file is not a .py file in core folder"
            exit 1
          fi
        done
        
        # Check utilities folder for .py files
        utilities_files=$(find utilities -type f)
        for file in $utilities_files; do
          if [[ ! $file == *.py ]]; then
            echo "Error: $file is not a .py file in utilities folder"
            exit 1
          fi
        done
        
        # Check sql folder for .sql files
        sql_files=$(find sql -type f)
        for file in $sql_files; do
          if [[ ! $file == *.sql ]]; then
            echo "Error: $file is not a .sql file in sql folder"
            exit 1
          fi
        done
        
        echo "✅ All file extensions are valid"

  python-syntax-check:
    name: Python Syntax Check
    runs-on: ubuntu-latest
    needs: validate-file-extensions
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Check Python syntax
      run: |
        echo "Checking Python syntax..."
        
        # Check all Python files in core and utilities
        python_files=$(find . -name "*.py" -type f)
        
        for file in $python_files; do
          echo "Checking syntax for $file"
          python -m py_compile $file
          if [ $? -ne 0 ]; then
            echo "❌ Syntax error in $file"
            exit 1
          fi
        done
        
        echo "✅ All Python files have valid syntax"
